-- 项目与任务（开发文档 3.4 M6 简化版：项目/任务 CRUD 与状态；WBS/甘特/资源负载随迭代）
CREATE TABLE project (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_number  VARCHAR(32)  NOT NULL,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    owner_id        BIGINT,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',   -- ACTIVE/CLOSED
    planned_start   DATE,
    planned_end     DATE,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    created_by      BIGINT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_project_number UNIQUE (project_number)
);

CREATE TABLE project_task (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT       NOT NULL,
    title         VARCHAR(255) NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'TODO',       -- TODO/DOING/DONE
    assignee_id   BIGINT,
    due_date      DATE,
    tenant_id     BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_project_task_project ON project_task (project_id);
