-- RBAC 基础表（兼容 PostgreSQL 16 与 H2 PostgreSQL 模式）
-- 模型：用户 --< user_role >-- 角色 --< role_permission >-- 权限点
-- M1 提供角色与用户绑定；权限点绑定接口随权限校验拦截器一起交付（见开发文档 10.2）

CREATE TABLE sys_role (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code  VARCHAR(64)  NOT NULL,
    role_name  VARCHAR(128) NOT NULL,
    builtin    SMALLINT     NOT NULL DEFAULT 0,   -- 内置角色不可删除
    tenant_id  BIGINT       NOT NULL DEFAULT 0,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_role_code UNIQUE (role_code)
);

CREATE TABLE sys_permission (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perm_code  VARCHAR(128) NOT NULL,             -- 形如 part:create / role:assign
    perm_name  VARCHAR(128) NOT NULL,
    CONSTRAINT uk_sys_permission_code UNIQUE (perm_code)
);

CREATE TABLE sys_user_role (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT uk_sys_user_role UNIQUE (user_id, role_id)
);
CREATE INDEX idx_sys_user_role_user ON sys_user_role (user_id);

CREATE TABLE sys_role_permission (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT uk_sys_role_permission UNIQUE (role_id, permission_id)
);

-- 内置角色
INSERT INTO sys_role (role_code, role_name, builtin) VALUES ('ADMIN', '系统管理员', 1);
INSERT INTO sys_role (role_code, role_name, builtin) VALUES ('ENGINEER', '工程师', 1);
INSERT INTO sys_role (role_code, role_name, builtin) VALUES ('VIEWER', '只读用户', 1);
