-- 组织/部门树（兼容 PostgreSQL 16 与 H2 PostgreSQL 模式）
-- path 为物化路径（如 /1/5/12/），用于"本部门及下级"的祖先/后代查询（ABAC 数据权限基础）

CREATE TABLE sys_org (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_code   VARCHAR(64)  NOT NULL,
    org_name   VARCHAR(128) NOT NULL,
    parent_id  BIGINT,                                -- NULL = 根节点
    path       VARCHAR(512) NOT NULL,                 -- 物化路径 /1/5/12/
    sort_order INT          NOT NULL DEFAULT 0,
    status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    tenant_id  BIGINT       NOT NULL DEFAULT 0,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_org_code UNIQUE (org_code)
);
CREATE INDEX idx_sys_org_path ON sys_org (path);
CREATE INDEX idx_sys_org_parent ON sys_org (parent_id);

-- 用户挂接组织
ALTER TABLE sys_user ADD COLUMN org_id BIGINT;
CREATE INDEX idx_sys_user_org ON sys_user (org_id);

-- 根组织
INSERT INTO sys_org (org_code, org_name, parent_id, path) VALUES ('ROOT', 'OpenForge', NULL, '/1/');

-- 组织管理权限点 + ADMIN 绑定
INSERT INTO sys_permission (perm_code, perm_name) VALUES ('org:manage', '组织管理');
INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id FROM sys_role r CROSS JOIN sys_permission p
WHERE r.role_code = 'ADMIN' AND p.perm_code = 'org:manage';
