package com.openforge.metadata.ddl;

import com.openforge.metadata.entity.MetaField;
import com.openforge.metadata.entity.MetaObject;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * 动态表 DDL 生成器（F2 设计 4 安全红线）：
 * 只做 CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS / CREATE INDEX IF NOT EXISTS，
 * 永不 DROP/RENAME/CHANGE（破坏性变更走新版本表迁移方案，本期不支持）。
 * 标识符必须先经 {@link IdentifierValidator} 白名单校验，生成器只做结构化拼接，不转义。
 * 兼容 PostgreSQL 16 与 H2（PostgreSQL 模式）。
 */
public final class DdlGenerator {

    /** 动态表名：dyn_ 前缀隔离自定义对象（F2 设计 2）。 */
    public static final String TABLE_PREFIX = "dyn_";

    private DdlGenerator() {
    }

    public static String tableNameOf(String objectKey) {
        return TABLE_PREFIX + objectKey;
    }

    /**
     * 首次发布建表语句：标准列（id/tenant_id/审计/软删）+ 元数据字段列 + 租户/软删索引，
     * 多条语句以 ";" 分隔，可整体执行。
     */
    public static String createTableSql(MetaObject object, List<MetaField> fields) {
        String table = tableNameOf(object.getObjectKey());
        StringBuilder sql = new StringBuilder();
        sql.append("CREATE TABLE IF NOT EXISTS ").append(table).append(" (\n")
                .append("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        for (MetaField field : fields) {
            sql.append(",\n    ").append(columnDef(field));
        }
        sql.append(",\n    tenant_id BIGINT NOT NULL DEFAULT 0")
                .append(",\n    created_by BIGINT")
                .append(",\n    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP")
                .append(",\n    updated_by BIGINT")
                .append(",\n    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP")
                .append(",\n    deleted SMALLINT NOT NULL DEFAULT 0")
                .append("\n)");
        sql.append(";\n")
                .append("CREATE INDEX IF NOT EXISTS idx_").append(table).append("_tenant ON ")
                .append(table).append(" (tenant_id)")
                .append(";\n")
                .append("CREATE INDEX IF NOT EXISTS idx_").append(table).append("_deleted ON ")
                .append(table).append(" (deleted)");
        return sql.toString();
    }

    /**
     * 增量变更语句：已存在的表仅追加缺失列（发布流水线比对库内已有列后调用）。
     * NOT NULL 列一律不带默认值回填——动态表历史行为空时由 F2-2 运行时保证写入完整。
     */
    public static List<String> addColumnSqls(String objectKey, List<MetaField> newFields) {
        String table = tableNameOf(objectKey);
        return newFields.stream()
                .map(field -> "ALTER TABLE " + table + " ADD COLUMN IF NOT EXISTS " + columnDef(field))
                .collect(Collectors.toCollection(ArrayList::new));
    }

    /** 单列定义: field_key TYPE [NOT NULL]。required 字段与 F2-2 运行时校验双重兜底。 */
    private static String columnDef(MetaField field) {
        FieldType type = FieldType.parse(field.getFieldType());
        StringBuilder col = new StringBuilder(field.getFieldKey()).append(' ').append(type.sqlType(field.getMaxLength()));
        if (field.getRequired() != null && field.getRequired() == 1) {
            col.append(" NOT NULL");
        }
        return col.toString();
    }
}
