package com.openforge.metadata.ddl;

import com.openforge.common.api.BizException;
import com.openforge.metadata.entity.MetaField;
import com.openforge.metadata.entity.MetaObject;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/** DDL 生成器（F2 设计 2/4）：类型映射、标准列、幂等语句、永不 DROP。 */
class DdlGeneratorTest {

    private MetaObject object(String key) {
        MetaObject o = new MetaObject();
        o.setObjectKey(key);
        o.setTableName(DdlGenerator.tableNameOf(key));
        return o;
    }

    private MetaField field(String key, FieldType type, boolean required, Integer maxLength) {
        MetaField f = new MetaField();
        f.setFieldKey(key);
        f.setFieldType(type.name());
        f.setRequired(required ? 1 : 0);
        f.setMaxLength(maxLength);
        return f;
    }

    @Test
    @DisplayName("建表语句：dyn_ 前缀 + 五类型映射 + 标准列 + NOT NULL + 租户/软删索引")
    void createTableSqlContainsTypeMappingAndStandardColumns() {
        String ddl = DdlGenerator.createTableSql(object("equipment"), List.of(
                field("name", FieldType.STRING, true, 128),
                field("purchase_price", FieldType.NUMBER, false, null),
                field("installed_at", FieldType.DATE, false, null),
                field("is_critical", FieldType.BOOLEAN, false, null),
                field("ref_part", FieldType.REFERENCE, false, null)));

        assertThat(ddl).startsWith("CREATE TABLE IF NOT EXISTS dyn_equipment (");
        assertThat(ddl).contains("name VARCHAR(128) NOT NULL");
        assertThat(ddl).contains("purchase_price NUMERIC(18,4)");
        assertThat(ddl).contains("installed_at TIMESTAMP");
        assertThat(ddl).contains("is_critical SMALLINT");
        assertThat(ddl).contains("ref_part BIGINT");
        // 标准列（F2 设计 2：所有表自动附加）
        assertThat(ddl).contains("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        assertThat(ddl).contains("tenant_id BIGINT NOT NULL DEFAULT 0");
        assertThat(ddl).contains("deleted SMALLINT NOT NULL DEFAULT 0");
        // 幂等索引
        assertThat(ddl).contains("CREATE INDEX IF NOT EXISTS idx_dyn_equipment_tenant ON dyn_equipment (tenant_id)");
        assertThat(ddl).contains("CREATE INDEX IF NOT EXISTS idx_dyn_equipment_deleted ON dyn_equipment (deleted)");
    }

    @Test
    @DisplayName("STRING 列宽：null/越界回退 255，合法值透传")
    void stringWidthFallback() {
        String ddl = DdlGenerator.createTableSql(object("t_demo"), List.of(
                field("a_name", FieldType.STRING, false, null),
                field("b_name", FieldType.STRING, false, 0),
                field("c_name", FieldType.STRING, false, 4001),
                field("d_name", FieldType.STRING, false, 64)));
        assertThat(ddl).contains("a_name VARCHAR(255)");
        assertThat(ddl).contains("b_name VARCHAR(255)");
        assertThat(ddl).contains("c_name VARCHAR(255)");
        assertThat(ddl).contains("d_name VARCHAR(64)");
    }

    @Test
    @DisplayName("增量语句：仅 ADD COLUMN IF NOT EXISTS，永不 DROP/RENAME/CHANGE")
    void addColumnSqlsAreAppendOnly() {
        List<String> sqls = DdlGenerator.addColumnSqls("equipment", List.of(
                field("location", FieldType.STRING, false, 255),
                field("weight", FieldType.NUMBER, true, null)));
        assertThat(sqls).containsExactly(
                "ALTER TABLE dyn_equipment ADD COLUMN IF NOT EXISTS location VARCHAR(255)",
                "ALTER TABLE dyn_equipment ADD COLUMN IF NOT EXISTS weight NUMERIC(18,4) NOT NULL");
        String all = String.join(";\n", sqls).toLowerCase();
        assertThat(all).doesNotContain("drop").doesNotContain("rename").doesNotContain(" modify ")
                .doesNotContain("change").doesNotContain("truncate");
    }

    @Test
    @DisplayName("防注入：非法标识符在进入生成器前被白名单拦截")
    void injectionIdentifiersNeverReachGenerator() {
        String[] attacks = {"name; DROP TABLE part", "name--x", "name/**/y", "name\", \"z", "na\\\"me"};
        for (String attack : attacks) {
            assertThatThrownBy(() -> IdentifierValidator.checkFieldKey(attack))
                    .as("注入载荷应被拦截: %s", attack)
                    .isInstanceOf(BizException.class);
        }
        assertThatThrownBy(() -> IdentifierValidator.checkObjectKey("x; CREATE TABLE hack (id INT)"))
                .isInstanceOf(BizException.class);
    }

    @Test
    @DisplayName("未知类型在生成器处兜底拒绝")
    void unknownTypeRejected() {
        MetaField bad = new MetaField();
        bad.setFieldKey("evil");
        bad.setFieldType("STRING); DROP TABLE part; --");
        bad.setRequired(0);
        assertThatThrownBy(() -> DdlGenerator.createTableSql(object("t_demo"), List.of(bad)))
                .isInstanceOf(BizException.class);
    }
}
