-- 物料版本快照表（发布时固化全字段，开发文档 7.1）
CREATE TABLE part_version (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id     BIGINT       NOT NULL,
    version     VARCHAR(16)  NOT NULL,
    snapshot    TEXT         NOT NULL,          -- 发布时刻全字段 JSON 快照
    state       VARCHAR(20)  NOT NULL,
    released_by BIGINT,
    released_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_part_version UNIQUE (part_id, version)
);
CREATE INDEX idx_part_version_part ON part_version (part_id);
