-- 刀1（替代件与主数据变更专项，设计文档 §4.1）：BOM 行号 + 替代组从表
-- 行号：变更单引用与 diff 对位的锚点；回填按 bom 分组、id 升序 1..n
ALTER TABLE bom_line ADD COLUMN position INT;
UPDATE bom_line SET position = (SELECT COUNT(*) FROM bom_line b2
                                WHERE b2.bom_id = bom_line.bom_id AND b2.id <= bom_line.id);
ALTER TABLE bom_line ALTER COLUMN position SET NOT NULL;

-- 替代组：主件行的从表（决策 D1）——替代件不产生额外用量，与主件共享需求数量
CREATE TABLE bom_line_substitute (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_line_id        BIGINT        NOT NULL,
    substitute_part_id BIGINT        NOT NULL,
    priority           INT           NOT NULL DEFAULT 1,
    qty_coefficient    NUMERIC(10,4) NOT NULL DEFAULT 1,
    condition_json     TEXT,
    last_change_id     BIGINT,
    tenant_id          BIGINT        NOT NULL DEFAULT 0,
    created_at         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_bom_sub UNIQUE (bom_line_id, substitute_part_id)
);
CREATE INDEX idx_bom_sub_part ON bom_line_substitute (substitute_part_id);
