-- 变更域初始表（ECR；ECO/ECN 随 M4 扩展，开发文档 7.3）
CREATE TABLE change_request (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ecr_number     VARCHAR(32)  NOT NULL,
    title          VARCHAR(255) NOT NULL,
    reason         TEXT,
    urgency        VARCHAR(10)  NOT NULL DEFAULT 'NORMAL',     -- LOW/NORMAL/HIGH
    affected_items TEXT,                                       -- 受影响对象引用 JSON（M4 结构化）
    state          VARCHAR(20)  NOT NULL DEFAULT 'SUBMITTED',  -- SUBMITTED/APPROVED/REJECTED
    workflow_instance_id BIGINT,                               -- 绑定的流程实例
    initiator_id   BIGINT,
    tenant_id      BIGINT       NOT NULL DEFAULT 0,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_change_request_number UNIQUE (ecr_number)
);
