-- 安全加固（方案 P-6：密码历史 E8 / 登录日志 F6 / 审计 F7）

CREATE TABLE sys_password_history (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    password_hash VARCHAR(128) NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_pwd_history_user ON sys_password_history (user_id, created_at DESC);

CREATE TABLE sys_login_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(64),
    success    SMALLINT     NOT NULL,           -- 1 成功 / 0 失败
    reason     VARCHAR(64),                     -- OK/BAD_CREDENTIALS/LOCKED/DISABLED
    ip         VARCHAR(45),
    user_agent VARCHAR(255),
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_login_log_time ON sys_login_log (created_at DESC);

CREATE TABLE sys_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id BIGINT,
    action      VARCHAR(64) NOT NULL,           -- USER_CREATE/USER_DISABLE/ROLE_ASSIGN/PERM_BIND/...
    target_type VARCHAR(30) NOT NULL,
    target_id   VARCHAR(64),
    detail      VARCHAR(500),
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_log_time ON sys_audit_log (created_at DESC);
