-- 用户表初始化（兼容 PostgreSQL 16 与 H2 PostgreSQL 模式）
CREATE TABLE sys_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL,
    password_hash VARCHAR(128) NOT NULL,
    display_name  VARCHAR(64),
    email         VARCHAR(128),
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    tenant_id     BIGINT       NOT NULL DEFAULT 0,
    created_by    BIGINT,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by    BIGINT,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted       SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT uk_sys_user_username UNIQUE (username)
);

CREATE INDEX idx_sys_user_tenant ON sys_user (tenant_id);
