-- A4 模块注册中心（设计 3.2）：部署即注册 / 停用即摘除 / 心跳判活
CREATE TABLE sys_module (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_key    VARCHAR(64)  NOT NULL,
    module_type   VARCHAR(20)  NOT NULL,               -- KERNEL/BUSINESS/AI/EXTENSION
    display_name  VARCHAR(128) NOT NULL,
    version       VARCHAR(32)  NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'ENABLED',  -- ENABLED/DISABLED/BROKEN
    routes        TEXT         NOT NULL,               -- JSON 数组
    menu          TEXT,                                -- JSON 数组（可空）
    dependencies  TEXT         NOT NULL DEFAULT '[]',  -- JSON 数组
    flyway_table  VARCHAR(64),
    health_path   VARCHAR(128),
    owner_ref     BIGINT,                              -- EXTENSION 型指向 meta_object.id
    registered_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    heartbeat_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_module_key UNIQUE (module_key)
);

-- 模块管理权限点 + ADMINS 绑定（幂等）
INSERT INTO sys_permission (perm_code, perm_name, perm_type, sort_order)
SELECT 'module:manage', '模块管理', 'OPERATION', 10
WHERE NOT EXISTS (SELECT 1 FROM sys_permission WHERE perm_code = 'module:manage');

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id FROM sys_role r
CROSS JOIN sys_permission p
WHERE r.role_code = 'ADMINS' AND p.perm_code = 'module:manage'
  AND NOT EXISTS (
      SELECT 1 FROM sys_role_permission rp
      WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );
