-- F3-1 多租户：租户主档 + 管理权限点
CREATE TABLE sys_tenant (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(64)  NOT NULL,
    tenant_name VARCHAR(128) NOT NULL,
    enabled     SMALLINT     NOT NULL DEFAULT 1,
    remark      VARCHAR(255),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_tenant_code UNIQUE (tenant_code)
);

INSERT INTO sys_permission (perm_code, perm_name, perm_type, sort_order)
SELECT 'tenant:manage', '租户管理', 'OPERATION', 11
WHERE NOT EXISTS (SELECT 1 FROM sys_permission WHERE perm_code = 'tenant:manage');

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id FROM sys_role r
CROSS JOIN sys_permission p
WHERE r.role_code = 'ADMINS' AND p.perm_code = 'tenant:manage'
  AND NOT EXISTS (
      SELECT 1 FROM sys_role_permission rp
      WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );
