-- B2 事件总线基础设施（docs/OpenForge-B2事件总线设计.md）
-- 两表均为平台级共享表（无租户列，已登记 TenantTables.GLOBAL_TABLES）

-- 幂等去重（消费侧）：at-least-once 投递下按 (event_id, consumer) 去重
CREATE TABLE sys_event_consumed (
    event_id    VARCHAR(64)  NOT NULL,
    consumer    VARCHAR(64)  NOT NULL,
    consumed_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_sys_event_consumed PRIMARY KEY (event_id, consumer)
);

-- 事务发件箱（P2 可靠性补齐用，本期建表不接线）：同事务落事件，relay 补发
CREATE TABLE sys_event_outbox (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64)  NOT NULL,
    topic       VARCHAR(64)  NOT NULL,
    tag         VARCHAR(64)  NOT NULL,
    payload     TEXT         NOT NULL,
    producer    VARCHAR(64)  NOT NULL,
    retry_count INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at     TIMESTAMP,
    CONSTRAINT uk_sys_event_outbox_event UNIQUE (event_id)
);
CREATE INDEX idx_sys_event_outbox_unsent ON sys_event_outbox (sent_at, id);
