-- 站内通知中心（v1.23 设计 §1.2）：平台级用户域设施，落 auth 迁移命名空间
-- （与 V23 事件基建同先例）。收件人与租户以 sys_user 记录为准，内部摄取免透传租户。

CREATE TABLE notify_message (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL DEFAULT 0,
    user_id     BIGINT       NOT NULL,            -- 收件人
    event_type  VARCHAR(64)  NOT NULL,            -- task.created / task.completed
    biz_type    VARCHAR(30),                      -- 跳转定位（PART_RELEASE/ECR/...）
    biz_id      BIGINT,
    title       VARCHAR(200) NOT NULL,
    content     VARCHAR(1000),
    read_flag   SMALLINT     NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_notify_inbox ON notify_message (user_id, read_flag, id);
