-- 编号规则引擎（兼容 PostgreSQL 16 与 H2 PostgreSQL 模式）
-- 规则段(segments)以 JSON 文本存储: [{"type":"CONST","value":"P"},{"type":"DATE","pattern":"yyyyMMdd"},{"type":"SEQ","length":5}]
-- 并发防重号: 计数器行锁(FOR UPDATE)事务内自增

CREATE TABLE sys_number_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_key     VARCHAR(64)  NOT NULL,           -- 业务标识, 如 part / ecr / doc
    rule_name    VARCHAR(128) NOT NULL,
    segments     TEXT         NOT NULL,           -- 段定义 JSON 数组
    reset_policy VARCHAR(20)  NOT NULL DEFAULT 'NONE',  -- NONE/DAILY/MONTHLY/YEARLY
    status       VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    tenant_id    BIGINT       NOT NULL DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_number_rule_key UNIQUE (rule_key)
);

CREATE TABLE sys_number_counter (
    rule_key      VARCHAR(64) NOT NULL,
    period        VARCHAR(16) NOT NULL DEFAULT '',  -- 重置周期标识(如 20260823), 不重置为空
    current_value BIGINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (rule_key, period)
);

-- 权限点 + ADMIN 绑定
INSERT INTO sys_permission (perm_code, perm_name) VALUES ('number:manage', '编号规则管理');
INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id FROM sys_role r CROSS JOIN sys_permission p
WHERE r.role_code = 'ADMIN' AND p.perm_code = 'number:manage';

-- 示例规则: 物料编码 P-yyyyMMdd-5位流水(按日重置)
INSERT INTO sys_number_rule (rule_key, rule_name, segments, reset_policy)
VALUES ('part', '物料编码', '[{"type":"CONST","value":"P"},{"type":"DATE","pattern":"yyyyMMdd"},{"type":"SEQ","length":5}]', 'DAILY');
