-- 文档域初始表（兼容 PostgreSQL 16 与 H2 PostgreSQL 模式）
CREATE TABLE doc_info (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_number      VARCHAR(32)  NOT NULL,
    title           VARCHAR(255) NOT NULL,
    doc_type        VARCHAR(32)  NOT NULL DEFAULT 'GENERAL',   -- GENERAL/SPEC/REPORT/DRAWING
    version_major   VARCHAR(8)   NOT NULL DEFAULT 'A',
    version_minor   INT          NOT NULL DEFAULT 0,
    lifecycle_state VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    checked_out_by  BIGINT,                                     -- 检出人（NULL=未检出）
    checked_out_at  TIMESTAMP,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    created_by      BIGINT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT uk_doc_number UNIQUE (doc_number)
);

CREATE TABLE doc_file (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_info_id  BIGINT       NOT NULL,
    file_name    VARCHAR(255) NOT NULL,
    storage_key  VARCHAR(512) NOT NULL,      -- 存储键（本地磁盘相对路径；M3 换 MinIO 对象键）
    file_size    BIGINT       NOT NULL,
    sha256       CHAR(64)     NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_doc_file_doc ON doc_file (doc_info_id);
