-- 元数据内核初始表（F2 设计 2：动态对象建模）
-- 注意: 本服务使用独立的 Flyway 历史表 flyway_metadata_history（多服务共享库, 见 application.yml）

CREATE TABLE meta_object (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_key    VARCHAR(64)  NOT NULL,                 -- API 路径段与表名后缀: equipment
    display_name  VARCHAR(128) NOT NULL,
    table_name    VARCHAR(64)  NOT NULL,                 -- dyn_equipment（dyn_ 前缀隔离自定义对象）
    status        VARCHAR(20)  NOT NULL DEFAULT 'DRAFT', -- DRAFT/PUBLISHED
    version       INT          NOT NULL DEFAULT 1,
    tenant_id     BIGINT       NOT NULL DEFAULT 0,
    created_by    BIGINT,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_meta_object_key UNIQUE (object_key)
);

CREATE TABLE meta_field (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id     BIGINT       NOT NULL,
    field_key     VARCHAR(64)  NOT NULL,                 -- 列名（snake_case，白名单校验）
    display_name  VARCHAR(128) NOT NULL,
    field_type    VARCHAR(20)  NOT NULL,                 -- STRING/NUMBER/DATE/BOOLEAN/REFERENCE
    required      SMALLINT     NOT NULL DEFAULT 0,
    max_length    INT,                                   -- STRING 列宽
    ref_object    VARCHAR(64),                           -- REFERENCE 指向的 object_key
    ref_field     VARCHAR(64),                           -- 引用展示字段（默认 id）
    sort_order    INT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_meta_field UNIQUE (object_id, field_key)
);
CREATE INDEX idx_meta_field_object ON meta_field (object_id);

-- 发布历史（含生成的 DDL 与定义快照，供回溯与 AI 溯源；写入随 F2-3 发布流水线启用）
CREATE TABLE meta_object_version (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id     BIGINT       NOT NULL,
    version       INT          NOT NULL,
    definition    TEXT         NOT NULL,                 -- 发布时的完整定义 JSON 快照
    ddl_text      TEXT         NOT NULL,                 -- 本次执行的 DDL 快照
    published_by  BIGINT,
    published_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_meta_object_version UNIQUE (object_id, version)
);
