-- F3-2 表单/列表设计器：界面布局（字段顺序/可见性/标签/列宽/跨列）
CREATE TABLE meta_form_layout (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id     BIGINT      NOT NULL,
    layout_type   VARCHAR(10) NOT NULL,               -- FORM / LIST
    layout        TEXT        NOT NULL,               -- JSON: {fields:[{fieldKey,visible,label,width,colSpan}]}
    updated_by    BIGINT,
    updated_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_meta_form_layout UNIQUE (object_id, layout_type)
);
