-- 物料域初始表（兼容 PostgreSQL 16 与 H2 PostgreSQL 模式）
-- 注意: 本服务使用独立的 Flyway 历史表 flyway_material_history（多服务共享库, 见 application.yml）

CREATE TABLE part_category (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(64)  NOT NULL,
    category_name VARCHAR(128) NOT NULL,
    parent_id     BIGINT,                                -- NULL = 根
    path          VARCHAR(512) NOT NULL,                 -- 物化路径 /1/5/
    attr_template TEXT,                                   -- 属性模板 JSON（M2-2 启用）
    sort_order    INT          NOT NULL DEFAULT 0,
    tenant_id     BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_part_category_code UNIQUE (category_code)
);
CREATE INDEX idx_part_category_path ON part_category (path);

CREATE TABLE part (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number     VARCHAR(32)  NOT NULL,
    name            VARCHAR(255) NOT NULL,
    name_en         VARCHAR(255),
    type            VARCHAR(20)  NOT NULL,               -- RAW/STANDARD/MADE/OUTSOURCED/SEMIFINISHED/PRODUCT
    category_id     BIGINT       NOT NULL,
    attrs           TEXT,                                 -- 动态属性 JSON（由分类属性模板约束, M2-2 校验）
    unit            VARCHAR(8),
    lifecycle_state VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',-- DRAFT/REVIEWING/RELEASED/FROZEN/PHASED_OUT
    version         VARCHAR(16)  NOT NULL DEFAULT 'A/1',
    security_level  VARCHAR(10)  NOT NULL DEFAULT 'PUBLIC',
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    created_by      BIGINT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by      BIGINT,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT uk_part_number UNIQUE (part_number)
);
CREATE INDEX idx_part_category ON part (category_id);
CREATE INDEX idx_part_state ON part (lifecycle_state);
