-- BOM 头与行（开发文档 7.1；M2 为 EBOM 单类型，多视图 M3 扩展）
CREATE TABLE bom (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_number      VARCHAR(32)  NOT NULL,
    parent_part_id  BIGINT       NOT NULL,
    bom_type        VARCHAR(10)  NOT NULL DEFAULT 'EBOM',
    version         VARCHAR(16)  NOT NULL DEFAULT 'A/1',
    lifecycle_state VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    created_by      BIGINT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT uk_bom_number UNIQUE (bom_number)
);
CREATE INDEX idx_bom_parent ON bom (parent_part_id);

CREATE TABLE bom_line (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_id         BIGINT        NOT NULL,
    child_part_id  BIGINT        NOT NULL,
    quantity       NUMERIC(14,4) NOT NULL,
    ref_des        TEXT,
    usage_type     VARCHAR(10)   NOT NULL DEFAULT 'NORMAL',  -- NORMAL/ALTERNATE/OPTIONAL
    effective_from DATE,
    effective_to   DATE,
    attrs          TEXT,
    tenant_id      BIGINT        NOT NULL DEFAULT 0,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_bom_line UNIQUE (bom_id, child_part_id)
);
CREATE INDEX idx_bom_line_bom ON bom_line (bom_id);
CREATE INDEX idx_bom_line_child ON bom_line (child_part_id);
