-- 集成编排器初始表（集成编排器 MVP 设计 §4；架构文档 8.2 连接器规范）
-- 注意: 本服务使用独立的 Flyway 历史表 flyway_connector_history（多服务共享库, 见 application.yml）

-- 连接器定义主档（spec_json 设计态；运行时只按 conn_definition_version 快照执行）
CREATE TABLE conn_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conn_code       VARCHAR(64)  NOT NULL,                  -- 租户内唯一 ^[a-z][a-z0-9_]{2,63}$
    conn_name       VARCHAR(128) NOT NULL,
    conn_type       VARCHAR(32)  NOT NULL,                  -- HTTP_REST / JDBC_READONLY（刀2）
    status          VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',  -- DRAFT/PUBLISHED/DISABLED
    current_version INT          NOT NULL DEFAULT 0,        -- 0=从未发布
    description     VARCHAR(512),
    spec_json       TEXT         NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    created_by      BIGINT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by      BIGINT,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT uk_conn_code UNIQUE (tenant_id, conn_code)
);

-- 不可变版本快照（发布时整份拷贝 spec_json；回滚 = 主档指回旧版本）
CREATE TABLE conn_definition_version (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT       NOT NULL DEFAULT 0,
    conn_id       BIGINT       NOT NULL,
    version       INT          NOT NULL,
    spec_json     TEXT         NOT NULL,
    published_by  BIGINT,
    published_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_conn_version UNIQUE (tenant_id, conn_id, version)
);
CREATE INDEX idx_conn_version_conn ON conn_definition_version (conn_id);

-- 凭据库（密文落库；API 永不回显明文；连接器 spec 以 cred_code 引用）
CREATE TABLE conn_credential (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cred_code     VARCHAR(64)  NOT NULL,
    cred_name     VARCHAR(128) NOT NULL,
    auth_type     VARCHAR(32)  NOT NULL,     -- BASIC/BEARER/API_KEY_HEADER/JDBC_PASSWORD（刀2）
    secret_cipher TEXT         NOT NULL,     -- AES-256-GCM base64(iv||ciphertext)
    extra_json    TEXT,                      -- 如 API_KEY 的 headerName
    tenant_id     BIGINT       NOT NULL DEFAULT 0,
    created_by    BIGINT,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by    BIGINT,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted       SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT uk_conn_cred_code UNIQUE (tenant_id, cred_code)
);

-- 执行日志（无界增长 → 保留期清理任务随刀2交付，默认 180 天，对齐登录日志惯例）
CREATE TABLE conn_exec_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT       NOT NULL DEFAULT 0,
    conn_id       BIGINT       NOT NULL,
    conn_version  INT          NOT NULL,     -- 0=设计态试运行（未发布版本）
    trigger_type  VARCHAR(16)  NOT NULL,     -- MANUAL / API
    status        VARCHAR(16)  NOT NULL,     -- SUCCESS/FAILED/TIMEOUT/BLOCKED
    http_status   INT,
    rows_returned INT,
    duration_ms   BIGINT       NOT NULL,
    error_msg     VARCHAR(1024),             -- 已脱敏（不含凭据/敏感头/响应体原文）
    trace_id      VARCHAR(64),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_conn_exec_log_conn ON conn_exec_log (tenant_id, conn_id, created_at DESC);
