-- AI 供应商配置（集成编排器 MVP 设计 §12.1 P2-1：AI API 配置器）
-- api_key 复用凭据加密体系（AES-256-GCM，同一主密钥）；enabled + priority 构成 ai-gateway 降级链

CREATE TABLE ai_provider (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_code VARCHAR(64)  NOT NULL,                -- ^[a-z][a-z0-9_]{2,63}$，租户内唯一
    provider_name VARCHAR(128) NOT NULL,
    base_url      VARCHAR(512) NOT NULL,                -- OpenAI 兼容 base_url（如 https://open.bigmodel.cn/api/paas/v4）
    api_key_enc   TEXT         NOT NULL,                -- AES-256-GCM base64(iv||ciphertext)
    model         VARCHAR(128) NOT NULL,                -- 默认对话模型（如 glm-4-flash）
    timeout_ms    INT          NOT NULL DEFAULT 60000,
    enabled       SMALLINT     NOT NULL DEFAULT 1,
    priority      INT          NOT NULL DEFAULT 100,    -- 降级链：数字越小越优先
    tenant_id     BIGINT       NOT NULL DEFAULT 0,
    created_by    BIGINT,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by    BIGINT,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted       SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT uk_ai_provider_code UNIQUE (tenant_id, provider_code)
);
