-- P2-2 事件/定时触发（集成编排器 MVP 设计 §12.2）：连接器触发配置 + 应用级死信。
-- 触发配置随发布进版本快照（不可变语义与 spec 一致）；DLQ 对齐 B2 幂等/死信语义，
-- 由应用层（非 broker %DLQ%）承载——触发执行失败即落死信，供人工重放/丢弃。

-- 连接器主档：触发配置（NONE=仅手动/API 调用）
ALTER TABLE conn_definition ADD COLUMN trigger_type VARCHAR(16) NOT NULL DEFAULT 'NONE';  -- NONE/EVENT/CRON
ALTER TABLE conn_definition ADD COLUMN trigger_json  TEXT;   -- EVENT:{topic,tag,params} CRON:{cron,params}

-- 版本快照同步携带触发配置（发布时的不可变拷贝）
ALTER TABLE conn_definition_version ADD COLUMN trigger_type VARCHAR(16) NOT NULL DEFAULT 'NONE';
ALTER TABLE conn_definition_version ADD COLUMN trigger_json  TEXT;

-- 触发执行死信（PENDING 待重放 / RESOLVED 重放成功 / DISCARDED 人工丢弃）
CREATE TABLE sys_connector_dlq (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT       NOT NULL DEFAULT 0,
    conn_id       BIGINT       NOT NULL,
    conn_code     VARCHAR(64)  NOT NULL,
    conn_version  INT          NOT NULL,
    trigger_type  VARCHAR(16)  NOT NULL,          -- EVENT / CRON
    source        VARCHAR(128),                  -- EVENT: eventId；CRON: 触发时刻 ISO-8601
    payload_json  TEXT         NOT NULL,         -- 触发入参（重放原样重投）
    error_msg     VARCHAR(1024),
    retry_count   INT          NOT NULL DEFAULT 0,
    status        VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    replayed_at   TIMESTAMP
);
CREATE INDEX idx_sys_connector_dlq ON sys_connector_dlq (tenant_id, status, id DESC);
