-- 测试专用：事件基础设施表（生产由 auth V23 建表；knowledge 自身 H2 测试历史不含 auth 迁移）
CREATE TABLE sys_event_consumed (
    event_id    VARCHAR(64)  NOT NULL,
    consumer    VARCHAR(64)  NOT NULL,
    consumed_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_sys_event_consumed PRIMARY KEY (event_id, consumer)
);

CREATE TABLE sys_event_outbox (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64)  NOT NULL,
    topic       VARCHAR(64)  NOT NULL,
    tag         VARCHAR(64)  NOT NULL,
    payload     TEXT         NOT NULL,
    producer    VARCHAR(64)  NOT NULL,
    retry_count INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at     TIMESTAMP,
    CONSTRAINT uk_sys_event_outbox_event UNIQUE (event_id)
);
