-- 图纸域初始表（v1.20.0；兼容 PostgreSQL 16 与 H2 PostgreSQL 模式）
-- 四表均带 tenant_id：租户拦截器（TenantLineInnerInterceptor）自动追加过滤条件，
-- 不入 TenantTables 全局清单（无跨租户共享语义）
CREATE TABLE drw_drawing (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drawing_number  VARCHAR(32)  NOT NULL,
    title           VARCHAR(255) NOT NULL,
    version_major   VARCHAR(8)   NOT NULL DEFAULT 'A',          -- 大版本 A/B/C（revise 递进）
    version_minor   INT          NOT NULL DEFAULT 0,            -- 小版本（检入驱动）
    lifecycle_state VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',      -- DRAFT/REVIEWING/RELEASED/OBSOLETE
    checked_out_by  BIGINT,                                     -- 检出人（NULL=未检出）
    checked_out_at  TIMESTAMP,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    created_by      BIGINT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT uk_drw_number UNIQUE (drawing_number)
);
CREATE INDEX idx_drw_drawing_tenant ON drw_drawing (tenant_id);

CREATE TABLE drw_drawing_file (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drawing_id   BIGINT       NOT NULL,
    file_name    VARCHAR(255) NOT NULL,
    storage_key  VARCHAR(512) NOT NULL,      -- 存储键（本地磁盘相对路径；MinIO 沿用同 key 约定）
    file_size    BIGINT       NOT NULL,
    sha256       CHAR(64)     NOT NULL,
    kind         VARCHAR(20)  NOT NULL DEFAULT 'ATTACHMENT', -- MAIN/PREVIEW/ATTACHMENT
    tenant_id    BIGINT       NOT NULL DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_drw_file_drawing ON drw_drawing_file (drawing_id);

-- 发布快照（对齐 material PartVersion 语义：RELEASED 时固化档案全字段 JSON）
CREATE TABLE drw_drawing_version (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drawing_id   BIGINT       NOT NULL,
    version      VARCHAR(16)  NOT NULL,      -- 形如 A/0、A/1、B/0
    snapshot     TEXT         NOT NULL,
    state        VARCHAR(20)  NOT NULL,
    released_by  BIGINT,
    tenant_id    BIGINT       NOT NULL DEFAULT 0,
    released_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_drw_version_drawing ON drw_drawing_version (drawing_id);

-- 图纸 ↔ 物料多对多关联（role：PART_DRAWING 零件图 / ASSEMBLY 装配图 / REFERENCE 参考）
CREATE TABLE drw_drawing_part (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drawing_id   BIGINT       NOT NULL,
    part_id      BIGINT       NOT NULL,
    part_number  VARCHAR(64)  NOT NULL,
    role         VARCHAR(20)  NOT NULL DEFAULT 'PART_DRAWING',
    tenant_id    BIGINT       NOT NULL DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_drw_drawing_part UNIQUE (drawing_id, part_id)
);
CREATE INDEX idx_drw_part_part ON drw_drawing_part (part_id);
