-- 知识库初始表（开发文档 7.5；M5 为单空间简化，多空间与密级随 M6）
CREATE TABLE knowledge_item (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(255) NOT NULL,
    content       TEXT         NOT NULL,
    summary       TEXT,
    source_type   VARCHAR(20)  NOT NULL DEFAULT 'MANUAL',  -- MANUAL/CHANGE_CASE/DOC
    source_ref    VARCHAR(255),
    tags          TEXT,                                     -- 逗号分隔标签
    quality_score NUMERIC(5,2) NOT NULL DEFAULT 60,
    usage_count   INT          NOT NULL DEFAULT 0,
    status        VARCHAR(20)  NOT NULL DEFAULT 'PUBLISHED',
    vector_id     VARCHAR(64),                              -- 向量存储键（M5 内存实现，M6 换 Milvus/pgvector）
    tenant_id     BIGINT       NOT NULL DEFAULT 0,
    created_by    BIGINT,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE knowledge_feedback (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_text  VARCHAR(512) NOT NULL,
    item_id     BIGINT,
    action      VARCHAR(20)  NOT NULL,   -- CLICK/DISMISS/ADOPT/RATE
    user_id     BIGINT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
