-- 流程引擎初始表（兼容 PostgreSQL 16 与 H2 PostgreSQL 模式；开发文档 7.4）
-- M3-1 定义格式为结构化 JSON（节点+边），bpmn-js 设计器就绪后同构映射

CREATE TABLE workflow_def (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    def_key      VARCHAR(64)  NOT NULL,           -- 业务标识 如 part-release
    name         VARCHAR(128) NOT NULL,
    version      INT          NOT NULL DEFAULT 1,
    status       VARCHAR(20)  NOT NULL DEFAULT 'PUBLISHED',  -- DRAFT/PUBLISHED/RETIRED
    definition   TEXT         NOT NULL,           -- 流程定义 JSON（节点+边）
    tenant_id    BIGINT       NOT NULL DEFAULT 0,
    created_by   BIGINT,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_workflow_def UNIQUE (def_key, version)
);

CREATE TABLE workflow_instance (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    def_key       VARCHAR(64)  NOT NULL,
    def_version   INT          NOT NULL,
    def_snapshot  TEXT         NOT NULL,           -- 启动时定义快照（在途实例不受新版本影响）
    biz_type      VARCHAR(30)  NOT NULL,           -- PART_RELEASE/ECR/...
    biz_id        BIGINT       NOT NULL,
    variables     TEXT,                            -- 流程变量 JSON
    state         VARCHAR(20)  NOT NULL DEFAULT 'RUNNING',  -- RUNNING/COMPLETED/REJECTED
    current_node  VARCHAR(64),                     -- 等待中的审批节点 id（RUNNING 时非空）
    initiator_id  BIGINT,
    started_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at      TIMESTAMP
);
CREATE INDEX idx_wfi_biz ON workflow_instance (biz_type, biz_id);
CREATE INDEX idx_wfi_state ON workflow_instance (state);

CREATE TABLE workflow_task (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id    BIGINT       NOT NULL,
    node_id        VARCHAR(64)  NOT NULL,
    node_name      VARCHAR(128),
    assignee_id    BIGINT,                          -- 直接指派（USER 类型）
    candidate_role VARCHAR(64),                     -- 角色认领（ROLE 类型）
    action         VARCHAR(20),                     -- APPROVE/REJECT（未完成为 NULL）
    comment        TEXT,
    acted_at       TIMESTAMP,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_wft_instance ON workflow_task (instance_id);
CREATE INDEX idx_wft_open_by_user ON workflow_task (assignee_id, action);
CREATE INDEX idx_wft_open_by_role ON workflow_task (candidate_role, action);
