-- 审批委托（v1.23 设计 §2）：查询期虚拟收件箱——规则生效期间被委托人待办并集委托人任务，
-- 不落库改派，停用/过期即刻失效。workflow_task.delegated_from 记录代办办理时的原指派人
-- （act 会用办理人覆盖 assignee_id，不补此列则原指派关系丢失）。

CREATE TABLE workflow_delegate (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT      NOT NULL DEFAULT 0,
    principal_id BIGINT      NOT NULL,          -- 委托人（创建者本人，服务端强制）
    agent_id     BIGINT      NOT NULL,          -- 被委托人
    def_key      VARCHAR(64),                   -- NULL=全部流程
    start_time   TIMESTAMP   NOT NULL,
    end_time     TIMESTAMP,                     -- NULL=长期有效
    enabled      SMALLINT    NOT NULL DEFAULT 1,
    remark       VARCHAR(200),
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_wf_delegate_no_self CHECK (principal_id <> agent_id)
);
CREATE INDEX idx_wfd_agent ON workflow_delegate (agent_id, enabled);
CREATE INDEX idx_wfd_principal ON workflow_delegate (principal_id, enabled);

ALTER TABLE workflow_task ADD COLUMN delegated_from BIGINT;
